;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-graphviz-dot-semi
        electric-newline-and-maybe-indent
        handle-switch-frame
        indent-for-tab-command
        prelude-move-beginning-of-line
        smex
        sp--self-insert-command
        sp-backward-delete-char
        sp-delete-char
        sp-kill-hybrid-sexp
        sp-kill-word
        undo-tree-visualizer-quit
        ))

(setq mc/cmds-to-run-once
      '(
        text-scale-increase
        ))
