;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        prelude-move-beginning-of-line
        sp--self-insert-command
        sp-backward-delete-char
        sp-delete-char
        sp-kill-hybrid-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
